layers=float(input('Enter the number of layers(2 to 5)= '))
length=float(input('Enter the side length of the top layer= '))
growth=float(input('Enter the growth of each layers(2 to 5)= '))
width=float(input('Enter the trunk width(odd number, 3 to 9)= '))
height=float(input('Enter the trunk height(4 to 10)= '))